# Generated by Django 3.1.5 on 2021-03-11 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210308_1120'),
        ('organization', '0002_auto_20210311_0940'),
        ('infra', '0002_auto_20210218_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infra.server'),
        ),
        migrations.AlterField(
            model_name='database',
            name='database_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infra.databasecluster'),
        ),
        migrations.AlterField(
            model_name='database',
            name='database_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infra.databasename'),
        ),
        migrations.AlterField(
            model_name='databaseinstance',
            name='database_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infra.databasecluster'),
        ),
        migrations.AlterField(
            model_name='databasename',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project'),
        ),
        migrations.AlterField(
            model_name='databasepermission',
            name='database_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infra.databasename'),
        ),
        migrations.AlterField(
            model_name='databasepermissionteamauthorization',
            name='database_permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infra.databasepermission'),
        ),
        migrations.AlterField(
            model_name='databasepermissionteamauthorization',
            name='legal_basis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.legalbase'),
        ),
        migrations.AlterField(
            model_name='databasepermissionteamauthorization',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.team'),
        ),
        migrations.AlterField(
            model_name='databasepermissionuserauthorization',
            name='database_permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infra.databasepermission'),
        ),
        migrations.AlterField(
            model_name='databasepermissionuserauthorization',
            name='legal_basis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.legalbase'),
        ),
        migrations.AlterField(
            model_name='databasepermissionuserauthorization',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.user'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.customer'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project'),
        ),
        migrations.AlterField(
            model_name='server',
            name='infrastructure_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infra.infrastructuresegment'),
        ),
        migrations.AlterField(
            model_name='service',
            name='infrastructure_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infra.infrastructuresegment'),
        ),
        migrations.AlterField(
            model_name='service',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project'),
        ),
    ]
