# Generated by Django 3.1.5 on 2021-01-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('project_number', models.BigIntegerField(blank=True, null=True)),
                ('old_project_numbers', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_id_source', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('support_contract_start', models.DateField(blank=True, null=True)),
                ('support_contract_end', models.DateField(blank=True, null=True)),
                ('support_contract_document_path', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('wpd_completion_date', models.DateField(blank=True, null=True)),
                ('path_wpd_document', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('path_release_document', models.CharField(blank=True, max_length=255, null=True)),
                ('destroy_date', models.DateField(blank=True, null=True)),
                ('path_destroy_document', models.CharField(blank=True, max_length=255, null=True)),
                ('security_scan_required', models.TextField(blank=True, null=True)),
                ('security_scan_date', models.DateField(blank=True, null=True)),
                ('path_security_scan_document', models.CharField(blank=True, max_length=255, null=True)),
                ('authorization_granter_email', models.CharField(blank=True, max_length=255, null=True)),
                ('path_authorization_matrix_document', models.CharField(blank=True, max_length=255, null=True)),
                ('privacy_status_updates', models.TextField()),
                ('lijst_remco', models.BigIntegerField()),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'project_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'project_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityAvailabilityLevel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'security_availability_levels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityConfidentialityLevel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'security_confidentiality_levels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityIntegrityLevel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'security_integrity_levels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupportContractStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'support_contract_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpdDocumentStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'wpd_document_status',
                'managed': False,
            },
        ),
    ]
