# Generated by Django 3.1.5 on 2021-03-11 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0003_auto_20210311_0940'),
        ('organization', '0002_auto_20210311_0940'),
        ('project', '0002_auto_20210308_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='account_holder_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_account_holder', to='organization.user'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.contact'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.customer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='information_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.informationmanager'),
        ),
        migrations.AlterField(
            model_name='project',
            name='infrastructure_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infra.infrastructuresegment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='personal_data_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.personaldatastatus'),
        ),
        migrations.AlterField(
            model_name='project',
            name='privacy_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.privacyofficer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_manager', to='organization.user'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projectstatus'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projecttype'),
        ),
        migrations.AlterField(
            model_name='project',
            name='security_availability_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.securityavailabilitylevel'),
        ),
        migrations.AlterField(
            model_name='project',
            name='security_confidentiality_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.securityconfidentialitylevel'),
        ),
        migrations.AlterField(
            model_name='project',
            name='security_integrity_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.securityintegritylevel'),
        ),
        migrations.AlterField(
            model_name='project',
            name='security_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.securityofficer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='support_contract_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.supportcontractstatus'),
        ),
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.team'),
        ),
        migrations.AlterField(
            model_name='project',
            name='wpd_document_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.wpddocumentstatus'),
        ),
    ]
