# Generated by Django 3.2.4 on 2021-06-14 14:37

import django.contrib.postgres.fields.citext
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210311_0940'),
    ]

    operations = [
        CITextExtension(),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-project_number']},
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255),
        ),
    ]
