# Generated by Django 3.2.6 on 2022-03-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_update_20220209'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='asset_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
