name: Opdrachten Team Dependabot

on:
  schedule: # Run the script on the 1st and 15th of every month
    - cron: '0 6 1,15 * *'
  workflow_dispatch: # Creates button on Github to trigger the workflow manually


jobs:
  dependabot:
    name: Templates
    uses: amsterdam/opdrachten-team-github-workflows/.github/workflows/dependabot.yml@v1
    secrets: inherit  # Inherit secrets from the repository. You need to define "SLACK_TOKEN" in settings -> secrets -> actions!
    with:
      check_diff: false  # Create a list of major upgrades. Needs the Makefile target "diff"
      slack_channel: 'opdrachten-dependabot'  # Slack channel to post release steps to
      timetell_code: 21127  # Timetell project id
      acceptance_pipeline: "https://ci.secure.amsterdam.nl/job/Opdrachten/job/Quotumtool/job/Quotumtool/job/main/"
      production_pipeline: "https://ci.secure.amsterdam.nl/job/Opdrachten/job/Quotumtool/job/Quotumtool/view/tags/"
      acceptance_urls: "https://acc.api.secure.amsterdam.nl/vergunningen/quota/kameromzettingen/dashboard/,
      https://acc.api.secure.amsterdam.nl/vergunningen/quota/bb/dashboard/"
      production_urls: "https://api.secure.amsterdam.nl/vergunningen/quota/kameromzettingen/dashboard/,
      https://api.secure.amsterdam.nl/vergunningen/quota/bb/dashboard/"

